### ISSUE TITLE
[1.1.2] Mouse controls and size upgrades

### ISSUE THREAD

**Issue by Revemohl** [AnimeniacYuuto/EnhancedInventories#35]
Just two things I noticed in the most recent version, I felt that I should report them here.
1. That thing you can do by picking up a stack of anything then holding either mouse button and dragging it across multiple inventory slots doesn't work inside EI inventories, for some reason.
2. Size upgrades don't get consumed after being used.

**Comment by AnimeniacYuuto** [comment]
on number 2 are you in creative?

**Comment by Revemohl** [comment]
Nope, in survival. I haven't tried any upgrade other than the tier 2 ones, though, so maybe the issue only happens with those?
Another thing I just found out is that if you place any chest (possibly lockers and cabinets too, but I forgot to check those) above tier 1 and break it, it will turn back into a tier 1 chest.

**Comment by AnimeniacYuuto** [comment]
Fixed with 03afe785690b00d5caca0294f6bdeceec3ea6e76 & f892c59d84075818156df7eb71055f9738dc380f

Update should be out by tomorrow

**Comment by Revemohl** [comment]
While playing just now, I noticed that now the problem is how size upgrades still don't get consumed if you use them on customized storage blocks (i.e. if you use the painter).

**Comment by AnimeniacYuuto** [comment]
okay I'll take a look

**Comment by AnimeniacYuuto** [comment]
Fixed, hopefully all the way this time with 47ebb935314fe6be26707a6225272ba36315d4f2
